/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Select": "选择",
    "Skill-Exchange": "技能交换",
    "Speed:": "速度:",
    "Spin the": "旋转",
    "Suspended:": "暂停：",
    "To buy": "去购买",
    "They pushed it": "他们推了它",
    "to receive:": "收到：",
    "to freelance": "成为自由职业者",
    "to Push Ads!": "推送广告！",
    "too far": "太远了",
    "upgrades!": "升级！",
    "When playing \"Banners Begone!\"": "当玩“横幅开始！”时",
    "your gameplay data can help find": "您的游戏数据有助于找到",
    "[BLOCK]": "[拦截]]",
    "Allow": "允许",
    "all space is occupied": "所有空间都被占用",
    "Another day on the web,": "又是一天在网上，",
    "Block the": "拦截",
    "Click": "点击",
    "Click Here": "点击这里",
    "GAME PAUSED": "游戏已暂停",
    "Hackathon": "黑客马拉松",
    "How to Play": "游戏玩法",
    "Import Save": "导入存档",
    "Left": "左",
    "Manual Save": "手动保存",
    "Max gain:": "最大收益：",
    "Mode": "模式",
    "Pause": "暂停",
    "Report a Bug": "报告Bug",
    "Reset Save": "重置存档",
    "resource types": "资源类型",
    "Right": "右",
    "Next": "下一个",
    "Mouse Button": "鼠标按钮",
    "Next Hackathon in:": "下一场黑客马拉松在：",
    "Next spawn in:": "下一次生产于：",
    "Hold": "按下",
    "Install AI Core": "安装 AI 核心",
    "Motor Accessibility": "电机辅助功能",
    "Record:": "记录：",
    "Review Analytics": "回顾分析",
    "today though,": "然而今天，",
    "Type:": "类型:",
    "Participate": "参加",
    "fan!": "粉丝！",
    "Exchange": "交换",
    "Export Save": "导出存档",
    "different": "不同",
    "Current gain:": "当前收益：",
    "Cryptography": "密码学",
    "another advertizing hell on the loose...": "另一个松散的广告地狱......",
    "As per Game Analytics Terms of Service, all collected data": "根据游戏分析服务条款，所有收集的数据",
    "can be used for analytics and marketing purposes": "可用于分析和营销目的",
    "can't even check the feed!": "甚至无法检查提要！",
    "Ad-Blocker": "广告拦截器",
    "Ad-Pusher": "广告发布商",
    "Agreement": "协议",
    "AI-Tech": "AI科技",
    "Do you allow anonymous collection and processing of this data?": "您是否允许匿名收集和处理这些数据？",
    "Forbid": "禁止",
    "Freelancing": "自由职业者",
    "Fullscreen": "全屏",
    "Game Analytics Privacy Policy": "游戏分析隐私政策",
    "gameplay weakpoints and improve them": "游戏弱点并加以改进",
    "Power:": "力量:",
    "block them all": "全部拦截",
    "Close": "关闭",
    "AD": "广告",
    "It's time to": "是时候",
    "let's show these ads": "让我们展示这些广告",
    "once and for all!": "一劳永逸！",
    "That's it,": "就是这样，",
    "who's the target audience here!": "谁是这里的目标观众！",
    "as normal if you want to!": "如果您愿意，可以像往常一样！",
    "Disable": "禁用",
    "Don't worry, you'll still be able to click": "别担心，您仍然可以点击",
    "Enable": "启用",
    "hold": "按下",
    "If you find trouble clicking all the time,": "如果您发现一直无法点击，",
    "Low": "低",
    "In this mode you can": "在这种模式下你可以",
    "to interact": "去互动",
    "with any tool automatically.": "自动使用任何工具。",
    "you can enable \"Motor Accessibility Mode\"": "您可以启用“电机辅助功能模式”",
    "and what's the most efficient way": "和什么是最有效的方法",
    "block them and buy minigame upgrades.": "拦截他们并购买迷你游戏升级。",
    "First, start from pushing ads with the button in the center.": "首先，从使用中间按钮推送广告开始。",
    "from the game board.": "从游戏面板。",
    "Have fun!": "玩得开心！",
    "If the ad is frozen and you're eager": "如果广告被冻结而你急切",
    "If you push fast, some ads will freeze,": "如果你推得快，一些广告会冻结，",
    "on it's blue border to call it in earlier.": "在它的蓝色边框上可以更早地调用它。",
    "Take your time to study each minigame.": "花点时间研究每个迷你游戏。",
    "the minigames to earn resources.": "小游戏赚取资源。",
    "to block it, you can click": "要拦截它，您可以单击",
    "to earn it's resources.": "来赚取它的资源。",
    "Understand what it does": "了解它的作用",
    "unraveling the game board.": "解开游戏面板。",
    "Use them to reduce ad costs,": "使用它们来降低广告成本，",
    "While the ads are frozen, use": "当广告被冻结时，使用",
    "Your goal is to clear all the ads": "您的目标是清除所有广告",
    "Sold Out!": "已售出！",
    "to see": "去查看",
    "Upgrades": "升级",
    "Game saved. No saving beyond this point!": "游戏已保存。 超过这一点就没有保存了！",
    "available": "可用",
    "AWAKEN": "觉醒",
    "Click!": "点击！",
    "Hackathon duration:": "黑客马拉松持续时间：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Max prize: ": "最大奖励：",
    "Effort per stage: ": "每个阶段的努力：",
    "Cost per core: ": "每个核心成本：",
    "Active cores: ": "可用核心：",
    "Competition stages: ": "竞争阶段：",
    "Spawn reward: ": "生产奖励：",
    "Hackathon duration: ": "黑客马拉松持续时间：",
    "Spin power: ": "旋转力量：",
    "Next spawn in: ": "距离下一次生产还有：",
    "Current prize: ": "当前奖励：",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " DISCOUNT]": " 折扣]",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+) ([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) ([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力收益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);